---
kind: pipeline
name: acceptance-tests

platform:
  os: linux
  arch: amd64

steps:
- name: build and vet the provider
  pull: always
  image: golang:1.15-buster
  commands:
  - make
  environment:
    GO111MODULE: on

- name: run acceptance tests
  pull: always
  image: golang:1.15-buster
  commands:
  - apt-get update; apt-get install netcat -y
  - until nc -z sonarqube 9000; do sleep 5; echo "Waiting for sonarqube to accept connections"; done
  - make testacc
  environment:
    GO111MODULE: on
    SONAR_HOST: sonarqube:9000
    SONAR_USER: admin
    SONAR_PASS: admin

services:
- name: sonarqube
  pull: default
  image: sonarqube:latest

trigger:
  event:
  - pull_request