---
kind: pipeline
name: acceptance-tests

platform:
  os: linux
  arch: amd64

steps:
- name: build and vet the provider
  pull: always
  image: golang:1.15
  commands:
  - make
  environment:
    GO111MODULE: on

- name: run acceptance tests
  pull: always
  image: golang:1.15
  commands:
  - make testacc
  environment:
    GO111MODULE: on

services:
- name: sonarqube
  pull: default
  image: sonarqube:latest

trigger:
  event:
  - pull_request