---
kind: pipeline
name: acceptance-tests

platform:
  os: linux
  arch: amd64

steps:
- name: vet
  pull: always
  image: golang:1.13
  commands:
  - make vet
  environment:
    GO111MODULE: on

- name: test
  pull: always
  image: golang:1.13
  commands:
  - make test
  environment:
    GO111MODULE: on

services:
- name: sonarqube
  pull: default
  image: sonarqube:latest

trigger:
  event:
  - pull_request