name: acceptance-tests-lts
on:
  push:

jobs:
  acceptance-tests:
    strategy:
      fail-fast: false
      matrix:
        image_tag: [community, developer, enterprise]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: build and vet the provider
        run: make
        env:
          GO111MODULE: on
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: run acceptance tests
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          TF_ACC: 1
          GO111MODULE: on
          SONAR_HOST: http://127.0.0.1:9000
          SONAR_USER: admin
          SONAR_PASS: admin
      - name: Run code coverage
        if: ${{ github.ref == 'refs/heads/master' && matrix.image_tag == 'developer'}}
        uses: codecov/codecov-action@v2
    services:
      sonarqube:
        image: sonarqube:${{ matrix.image_tag }}
        ports:
          - 9000:9000
